// react-examples/examples/with-background-transformer/src/App.tsx
import { useEffect } from 'react';
import { RtkMeeting } from '@cloudflare/realtimekit-react-ui';
import { useRealtimeKitClient } from '@cloudflare/realtimekit-react';
import RealtimeKitVideoBackgroundTransformer from '@cloudflare/realtimekit-virtual-background';

declare global {
  interface Window {
    meeting: any;
  }
}

function App() {
  const [meeting, initMeeting] = useRealtimeKitClient();

  useEffect(() => {
    const searchParams = new URL(window.location.href).searchParams;

    const authToken = searchParams.get('authToken');

    if (!authToken) {
      alert(
        "An authToken wasn't passed, please pass an authToken in the URL query to join a meeting."
      );
      return;
    }

    const baseURI = searchParams.get('baseURI') || import.meta.env.VITE_BASE_URL;
    const logInConsole = searchParams.get('logInConsole') === 'true';

    (
      initMeeting({
        authToken,
        baseURI,
        modules: { devTools: { logs: logInConsole } },
      }) as any
    ).then(async (meeting: any) => {
      window.meeting = meeting;

      /**
       * To customise RealtimeKitVideoBackgroundTransformer configs, please refer to https://www.npmjs.com/package/@cloudflare/realtimekit-virtual-background?activeTab=readme.
       * 
      */
      const videoBackgroundTransformer =
        await RealtimeKitVideoBackgroundTransformer.init({
          meeting,
          segmentationConfig: {
            pipeline: 'canvas2dCpu', // 'webgl2' | 'canvas2dCpu'
          },
        });

      // The video-background-transformer provides two functionalities
      // 1. Add background blur
      // 2. Add a background image

      // 1. To add background blur, with strength of 10
      meeting.self.addVideoMiddleware(
        await videoBackgroundTransformer.createBackgroundBlurVideoMiddleware(10)
      );

      // 2. To add a background image
      // meeting.self.addVideoMiddleware(
      //   await videoBackgroundTransformer.createStaticBackgroundVideoMiddleware(
      //     'https://rtk-assets.realtime.cloudflare.com/backgrounds/bg_1.jpg'
      //   )
      // );

      // We have the following set of images for your immediate use:
      // https://rtk-assets.realtime.cloudflare.com/backgrounds/bg_1.jpg
      // https://rtk-assets.realtime.cloudflare.com/backgrounds/bg_2.jpg
      // https://rtk-assets.realtime.cloudflare.com/backgrounds/bg_3.jpg
      // https://rtk-assets.realtime.cloudflare.com/backgrounds/bg_4.jpg
      // https://rtk-assets.realtime.cloudflare.com/backgrounds/bg_5.jpg
      // https://rtk-assets.realtime.cloudflare.com/backgrounds/bg_6.jpg
      // https://rtk-assets.realtime.cloudflare.com/backgrounds/bg_7.jpg
    });
  }, []);

  // By default this component will cover the entire viewport.
  // To avoid that and to make it fill a parent container, pass the prop:
  // `mode="fill"` to the component.
  return <RtkMeeting meeting={meeting!} />;
}

export default App;

// angular-examples/examples/with-video-transformer/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { RtkMeeting, registerAddons } from '@cloudflare/realtimekit-angular-ui';
import RealtimeKitClient from '@cloudflare/realtimekit';
import VideoBackground from '@cloudflare/realtimekit-ui-addons/video-background';
import { environment } from '../environments/environment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'with-video-transformer';

  @ViewChild('meeting') $meetingEl!: RtkMeeting;

  async ngAfterViewInit() {
    const searchParams = new URL(window.location.href).searchParams;

    const authToken = searchParams.get('authToken');

    console.log({ authToken });

    if (!authToken) {
      alert(
        "An authToken wasn't passed, please pass an authToken in the URL query to join a meeting."
      );
      return;
    }

    const baseURI = searchParams.get('baseURI') || environment.baseUrl;
    const logInConsole = searchParams.get('logInConsole') === 'true';

    const meeting = await RealtimeKitClient.init({
      authToken,
      baseURI,
      modules: { devTools: { logs: logInConsole } },
    });

    this.$meetingEl.meeting = meeting;

    const videoBackground = await VideoBackground.init({
      modes: ["blur", "virtual", "random"],
      blurStrength: 30, // 0 - 100 for opacity
      meeting: meeting!,
      images: [
          "https://images.unsplash.com/photo-1487088678257-3a541e6e3922?q=80&w=2874&auto=format&fit=crop&ixlib=rb-4.0.3",
          "https://images.unsplash.com/photo-1496715976403-7e36dc43f17b?q=80&w=2848&auto=format&fit=crop&ixlib=rb-4.0.3",
          "https://images.unsplash.com/photo-1600431521340-491eca880813?q=80&w=2938&auto=format&fit=crop&ixlib=rb-4.0.3"
      ],
      randomCount: 10,
    });

    const newConfig = registerAddons([videoBackground], meeting);

    this.$meetingEl.config = newConfig;
  }
}
