// angular-examples/examples/create-your-own-ui/src/app/app.component.ts
import { Component, OnInit, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/common';
import { StatesService } from './services/states.service';
import RealtimeKitClient from '@cloudflare/realtimekit';
import { environment } from '../environments/environment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  meeting: any = null;

  constructor(
    private statesService: StatesService,
    @Inject(DOCUMENT) private document: Document
  ) {}

  async ngOnInit() {
    await this.initializeMeeting();
  }

  private async initializeMeeting() {
    const searchParams = new URLSearchParams(this.document.defaultView?.location.search);
    const authToken = searchParams.get('authToken');

    if (!authToken) {
      alert(
        "An authToken wasn't passed, please pass an authToken in the URL query to join a meeting."
      );
      return;
    }

    if (!this.meeting) {
      try {
        // Initialize RealtimeKit client
        const baseURI = searchParams.get('baseURI') || environment.baseUrl;
        const logInConsole = searchParams.get('logInConsole') === 'true';

        const meeting = await RealtimeKitClient.init({
          authToken,
          baseURI,
          modules: { devTools: { logs: logInConsole } },
        });

        this.meeting = meeting;

        // Expose meeting object to window for debugging
        Object.assign(this.document.defaultView as any, {
          meeting: this.meeting,
        });

      } catch (error) {
        console.error('Failed to initialize meeting:', error);
      }
    }
  }

  onRtkStatesUpdate(event: any) {
    this.statesService.setStates(event.detail);
  }
}

// react-examples/examples/clubhouse/src/App.tsx
import { useEffect } from 'react';
import { RealtimeKitProvider, useRealtimeKitClient } from '@cloudflare/realtimekit-react';
import Meeting from './components/Meeting';
import { provideRtkDesignSystem, RtkUiProvider } from '@cloudflare/realtimekit-react-ui';

function App() {
  const [meeting, initMeeting] = useRealtimeKitClient();

  useEffect(() => {
    provideRtkDesignSystem(document.body, {
      theme: 'light'
    });

    const searchParams = new URL(window.location.href).searchParams;

    const authToken = searchParams.get('authToken');

    if (!authToken) {
      alert(
        "An authToken wasn't passed, please pass an authToken in the URL query to join a meeting."
      );
      return;
    }

    const baseURI = searchParams.get('baseURI') || import.meta.env.VITE_BASE_URL;
    const logInConsole = searchParams.get('logInConsole') === 'true';

    initMeeting({
      authToken,
      baseURI,
      defaults: {
        video: false,
        audio: false,
      },
      modules: { devTools: { logs: logInConsole } },
    }).then((m) => {
      Object.assign(window, { meeting: m });
    });
  }, []);

  return (
    <div className="w-full max-w-lg mx-auto h-full bg-gray-100">
      <RealtimeKitProvider value={meeting} fallback={<div>loading...</div>}>
        <RtkUiProvider meeting={meeting} showSetupScreen={window.location.search.includes('showSetupScreen')}>
          <Meeting />
        </RtkUiProvider>
      </RealtimeKitProvider>
    </div>
  );
}

export default App;
