// recording-sdk-app-examples/angular-examples/screenshare-focused-with-snapshot-capture/src/app/app.component.ts
import { Component, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/common';
import RealtimeKitClient from '@cloudflare/realtimekit';
import { RealtimeKitRecording } from '@cloudflare/realtimekit-recording-sdk';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  meeting: RealtimeKitClient | null = null;

  constructor(@Inject(DOCUMENT) private document: Document) {}

  async ngAfterViewInit() {
    const searchParams = new URLSearchParams(this.document.defaultView?.location.search);

    const authToken = searchParams.get('authToken');

    if (!authToken) {
      alert(
        "An authToken wasn't passed, please pass an authToken in the URL query to join a meeting."
      );
      return;
    }

    const baseURI = searchParams.get('baseURI');

    const recordingSDK = new RealtimeKitRecording({});
    const meetingObj = await RealtimeKitClient.init({
      authToken,
      defaults: {
        video: false,
        audio: false,
      },
      baseURI: baseURI ?? 'realtime.cloudflare.com',
    });

    await recordingSDK.init(meetingObj);
    this.meeting = meetingObj;

    Object.assign(this.document.defaultView as any, { meeting: this.meeting });
  }
}

<app-recording-view
  *ngIf="meeting"
  [meeting]="meeting"
></app-recording-view>
<div *ngIf="!meeting" style="display: flex; justify-content: center; align-items: center; height: 100vh;">
  Loading...
</div>

// recording-sdk-app-samples/react-examples/record-single-preset/src/App.tsx
import { useEffect } from "react";
import {
  RealtimeKitProvider,
  useRealtimeKitClient,
} from "@cloudflare/realtimekit-react";
import RecordingView from "./components/RecordingView";
import { RealtimeKitRecording } from "@cloudflare/realtimekit-recording-sdk";

function App() {
  const [meeting, initMeeting] = useRealtimeKitClient();

  useEffect(() => {
    async function setupRealtimeKitMeeting() {
      const searchParams = new URL(window.location.href).searchParams;

      const authToken = searchParams.get("authToken");

      if (!authToken) {
        alert(
          "An authToken wasn't passed, please pass an authToken in the URL query to join a meeting.",
        );
        return;
      }

      const baseURI = searchParams.get("baseURI");

      const recordingSDK = new RealtimeKitRecording({});
      const meetingObj = await initMeeting({
        authToken,
        defaults: {
          video: false,
          audio: false,
        },
        baseURI: baseURI ?? "realtime.cloudflare.com",
      });
      if (!meetingObj) {
        return;
      }
      await recordingSDK.init(meetingObj);
    }
    if (!meeting) {
      setupRealtimeKitMeeting();
    }
  }, [meeting]);

  Object.assign(window, { meeting });

  // By default this component will cover the entire viewport.
  // To avoid that and to make it fill a parent container, pass the prop:
  // `mode="fill"` to the component.
  return (
    <RealtimeKitProvider value={meeting} fallback={<div>Loading...</div>}>
      <RecordingView />
    </RealtimeKitProvider>
  );
}

export default App;
