// recording-sdk-app-examples/react-examples/screenshare-focused-with-snapshot-capture/src/components/RecordingView.tsx
import { RtkAvatar, RtkParticipantsAudio, RtkParticipantTile, RtkScreenshareView } from "@cloudflare/realtimekit-react-ui";
import { useRealtimeKitMeeting, useRealtimeKitSelector } from "@cloudflare/realtimekit-react";
import { useEffect, useState } from "react";

export default function RecordingView() {
    const { meeting } = useRealtimeKitMeeting();

    const [size] = useState({ height: '120px', width: '120px' });

    const activeParticipants = useRealtimeKitSelector((meeting) =>
        meeting.participants.active.toArray()
    );

    const pinnedParticipants = useRealtimeKitSelector((meeting) =>
        meeting.participants.pinned.toArray()
    );

    const screensharedParticipants = useRealtimeKitSelector((meeting) =>
        meeting.participants.joined.toArray().filter((p) => p.screenShareEnabled)
    );

    // show pinned participants first
    const participants = [
        ...pinnedParticipants,
        ...activeParticipants.filter((p) => !pinnedParticipants.includes(p)),
    ];

    const hasScreenshare = screensharedParticipants.length > 0;

    useEffect(() => {
        if(!meeting){
            return;
        }

        const captureParticipantSnapshotAndPost = async () => {
            const participants = meeting.participants.active.toArray().filter((e) => e.videoEnabled && e.presetName && e.presetName.indexOf(import.meta.env.VITE_PRESET_NAME_FOR_THUMBNAIL) > -1);
            const canvasElement = document.createElement('canvas');
		    const videoElement = document.createElement('video');

            for(let participant of participants){
                try{
                    const track = participant.videoTrack;
                    const stream = new MediaStream();
                    stream.addTrack(track);

                    videoElement.srcObject = stream;
		            videoElement.autoplay = true;
                    videoElement.muted = true;

                    try {
                        await videoElement.play();
                    } catch (ex) {
                        // Ignore
                    }

                    const canvasCtx = canvasElement.getContext('2d');

                    const trackSettings = track.getSettings();
                    const width = trackSettings?.width ?? 1920;
                    const height = trackSettings?.height ?? 1080;

                    videoElement.height = height;
                    videoElement.width = width;
                    canvasElement.width = width;
                    canvasElement.height = height;
                    canvasCtx!.drawImage(videoElement, 0, 0, width, height);
                    
                    const dataURL = canvasElement!.toDataURL("image/jpeg")
                    
                    /**
                     * NOTE(ravindra-cloudflare): alter the body params as per your need.
                     * Below is just a example
                     */
                    await fetch(import.meta.env.VITE_THUMBNAIL_POST_ENDPOINT, {
                        method: 'POST',
                        headers: {
                        'Content-Type': 'application/json',
                        },
                        body: JSON.stringify({
                            "room_sid": meeting.meta.meetingId,
                            "file_content": dataURL
                        }),
                    });

                }catch{
                    // For now, do nothing
                }
            }
        }

        let intervalId = setInterval(async () => {
            await captureParticipantSnapshotAndPost();
        }, +import.meta.env.VITE_THUMBNAIL_TIME_INTERVAL);

        return () => {
            clearInterval(intervalId);
        }
    }, [meeting]);

    return (<main
        style={{
            display: "flex",
            position: "relative",
            paddingTop: "0rem",
            flexWrap: "wrap",
            flexShrink: "0",
            justifyContent: "center",
            alignContent: "center",
            width: "100vw",
            height: "100vh"
        }}
    >
        {hasScreenshare && (
            <RtkScreenshareView
                meeting={meeting}
                participant={screensharedParticipants[0]}
                hideFullScreenButton={true}
            />
        )}
        <div
            style={{
                height: `calc(${size.height} + 1.25rem)`,
                display: "flex",
                position: "fixed",
                bottom: "0",
                zIndex: "10",
                paddingLeft: "2.5rem",
                paddingRight: "2.5rem",
                verticalAlign: "middle",
                justifyContent: "flex-start",
                width: "100%",
                gap: "1rem",
                marginLeft:"2rem"
            }}
        >
            {participants.map((participant) => {
                return (
                    <div
                        key={participant.id}
                        style={{ ...size, borderRadius: "9999px" }}
                    >
                        <RtkParticipantTile
                            meeting={meeting}
                            participant={participant}
                            key={participant.id}
                            style={{
                                ...size,
                                transitionProperty: "all",
                                borderRadius: "9999px",
                                borderWidth: "1px",
                            }}
                        >
                            <RtkAvatar participant={participant} />
                        </RtkParticipantTile>
                    </div>
                );
            })}
        </div>
        <RtkParticipantsAudio meeting={meeting} />
    </main>)
}

// recording-sdk-app-examples/angular-examples/screenshare-focused-with-snapshot-capture/src/app/components/recording-view.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import RealtimeKitClient from '@cloudflare/realtimekit';
import type { RTKParticipant } from '@cloudflare/realtimekit';
import { environment } from '../../environments/environment';

@Component({
  selector: 'app-recording-view',
  templateUrl: './recording-view.component.html',
  styleUrls: ['./recording-view.component.css'],
})
export class RecordingViewComponent implements OnInit, OnDestroy {
  @Input() meeting!: RealtimeKitClient;

  participants: RTKParticipant[] = [];
  screensharedParticipants: RTKParticipant[] = [];
  hasScreenshare = false;

  readonly bubbleSize = { height: '120px', width: '120px' };

  private intervalId: ReturnType<typeof setInterval> | null = null;

  ngOnInit() {
    this.updateParticipants();
    this.meeting.participants.joined.addListener('participantJoined', () => this.updateParticipants());
    this.meeting.participants.joined.addListener('participantLeft', () => this.updateParticipants());
    this.meeting.participants.joined.addListener('screenShareUpdate', () => this.updateParticipants());

    this.startSnapshotCapture();
  }

  ngOnDestroy() {
    this.meeting.participants.joined.removeAllListeners('participantJoined');
    this.meeting.participants.joined.removeAllListeners('participantLeft');
    this.meeting.participants.joined.removeAllListeners('screenShareUpdate');

    if (this.intervalId) {
      clearInterval(this.intervalId);
    }
  }

  private updateParticipants() {
    const joined = this.meeting.participants.joined.toArray();
    const pinned = this.meeting.participants.pinned.toArray();
    const active = this.meeting.participants.active.toArray();

    // show pinned participants first
    this.participants = [
      ...pinned,
      ...active.filter((p) => !pinned.includes(p)),
    ];

    this.screensharedParticipants = joined.filter(
      (p) => p.screenShareEnabled
    );

    this.hasScreenshare = this.screensharedParticipants.length > 0;
  }

  private startSnapshotCapture() {
    this.intervalId = setInterval(async () => {
      await this.captureParticipantSnapshotAndPost();
    }, environment.thumbnailTimeInterval);
  }

  private async captureParticipantSnapshotAndPost() {
    const participants = this.meeting.participants.active
      .toArray()
      .filter(
        (e: any) =>
          e.videoEnabled &&
          e.presetName &&
          e.presetName.indexOf(environment.presetNameForThumbnail) > -1
      );

    const canvasElement = document.createElement('canvas');
    const videoElement = document.createElement('video');

    for (const participant of participants) {
      try {
        const track = (participant as any).videoTrack;
        const stream = new MediaStream();
        stream.addTrack(track);

        videoElement.srcObject = stream;
        videoElement.autoplay = true;
        videoElement.muted = true;

        try {
          await videoElement.play();
        } catch (ex) {
          // Ignore
        }

        const canvasCtx = canvasElement.getContext('2d');

        const trackSettings = track.getSettings();
        const width = trackSettings?.width ?? 1920;
        const height = trackSettings?.height ?? 1080;

        videoElement.height = height;
        videoElement.width = width;
        canvasElement.width = width;
        canvasElement.height = height;
        canvasCtx!.drawImage(videoElement, 0, 0, width, height);

        const dataURL = canvasElement.toDataURL('image/jpeg');

        /**
         * NOTE: alter the body params as per your need.
         * Below is just an example
         */
        await fetch(environment.thumbnailPostEndpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            room_sid: this.meeting.meta.meetingId,
            file_content: dataURL,
          }),
        });
      } catch {
        // For now, do nothing
      }
    }
  }

  trackById(_index: number, participant: RTKParticipant): string {
    return participant.id;
  }
}

<main
  style="display: flex; position: relative; padding-top: 0; flex-wrap: wrap; flex-shrink: 0; justify-content: center; align-content: center; width: 100vw; height: 100vh;"
>
  <rtk-screenshare-view
    *ngIf="hasScreenshare"
    [meeting]="meeting"
    [participant]="screensharedParticipants[0]"
    [hideFullScreenButton]="true"
  ></rtk-screenshare-view>

  <div
    [style.height]="'calc(' + bubbleSize.height + ' + 1.25rem)'"
    style="display: flex; position: fixed; bottom: 0; z-index: 10; padding-left: 2.5rem; padding-right: 2.5rem; vertical-align: middle; justify-content: flex-start; width: 100%; gap: 1rem; margin-left: 2rem;"
  >
    <div
      *ngFor="let participant of participants; trackBy: trackById"
      [style.height]="bubbleSize.height"
      [style.width]="bubbleSize.width"
      style="border-radius: 9999px;"
    >
      <rtk-participant-tile
        [meeting]="meeting"
        [participant]="participant"
        [style.height]="bubbleSize.height"
        [style.width]="bubbleSize.width"
        style="transition-property: all; border-radius: 9999px; border-width: 1px;"
      >
        <rtk-avatar [participant]="participant"></rtk-avatar>
      </rtk-participant-tile>
    </div>
  </div>

  <rtk-participants-audio [meeting]="meeting"></rtk-participants-audio>
</main>
